server:
  port: 8082

spring:
  application:
    name: note-service
  data:
    mongodb:
      uri: mongodb+srv://admin:admin@cluster0.twkounu.mongodb.net
      database: Note
      auto-index-creation: true
  redis:
    host: redis-14025.c294.ap-northeast-1-2.ec2.redns.redis-cloud.com
    port: 14025
    password: cCgwAqRWzyJEu9nptVhQsZcjSDSU6uMx
    database: 0
    timeout: 10000

springdoc:
  swagger-ui:
    path: /swagger
  api-docs:
    path: /api-docs
